// Generated by CoffeeScript 1.6.3
(function() {
  exports.secret = 1971;

  exports.hello = function() {
    return "Hello Server 2";
  };

  exports.test = {
    alpha: function() {
      return console.log('Alpha Server Test');
    },
    beta: function() {
      return "Server Warning";
    }
  };

}).call(this);
